### ISSUE TITLE
이건머에여

### ISSUE THREAD

**Issue by eunii2** [yugyeong2/OSSCA-LoxiLB#1]

**Comment by yugyeong2** [comment]
https://github.com/yugyeong2/OSSCA-LoxiLB/blob/8cb7aef49bc99fef05704551be929ff3a6c0d32b/README.md?plain=1#L1-L14

Readme 추가했습니다. 감사합니다.

![제리인사](https://github.com/user-attachments/assets/da9f480f-8ede-45a4-b594-01499f3436ac)

**Comment by eunii2** [comment]
아주 좋습니다:)
